---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmreleases.helm.bitnami.com
spec:
  group: helm.bitnami.com
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    singular: helmrelease
  scope: Namespaced
  version: v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
spec:
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helm
        name: tiller
    spec:
      containers:
      - args:
        - --listen=localhost:44134
        command:
        - /tiller
        env:
        - name: TILLER_NAMESPACE
          value: kube-system
        - name: TILLER_HISTORY_MAX
          value: "0"
        image: gcr.io/kubernetes-helm/tiller:v2.8.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /liveness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        name: tiller
        ports: []
        readinessProbe:
          httpGet:
            path: /readiness
            port: 44135
          initialDelaySeconds: 1
          timeoutSeconds: 1
        resources: {}
      - args:
        - --home=/helm
        - --host=localhost:44134
        - --logtostderr
        command:
        - /controller
        env:
        - name: TMPDIR
          value: /helm
        image: bitnami/helm-crd-controller:latest
        name: controller
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /helm
          name: home
      volumes:
      - emptyDir: {}
        name: home
status: {}
